const serviceNames = [
 "Plumber",
  "Electrician",
  "Carpenter",
  "AC Repair",
  "Painting",
  "Floor Cleaning",
  "Washroom Cleaning",
  "Washing Machine Repair",
  "Refrigerator Repair",
  "TV Repair",
  "Pest Control",
  "Water Purifier Repair",
  "Stove Repair",
  "Microwave Repair",
  "Salon Men",
  "Salon Women",
  "Hair Cutting",
  "Hair Styling",
  "Hair Coloring",
  "Facial Service",
  "Makeup Artist",
  "Bridal Makeup",
  "Spa Service",
  "Massage Therapy",
  "Pedicure",
  "Manicure",
  "Sofa Cleaning",
  "Carpet Cleaning",
  "Curtain Cleaning",
  "Mattress Cleaning",
  "Kitchen Cleaning",
  "Deep Home Cleaning",
  "Office Cleaning",
  "Glass Cleaning",
  "Tank Cleaning",
  "Water Tank Repair",
  "Roof Cleaning",
  "Garden Cleaning",
  "House Shifting",
  "Packers and Movers",
  "Bike Repair",
  "Car Repair",
  "Car Wash",
  "Car Detailing",
  "Battery Replacement",
  "Tyre Repair",
  "Wheel Alignment",
  "Generator Repair",
  "Inverter Repair",
  "CCTV Installation",
  "Security System Setup",
  "Computer Repair",
  "Laptop Repair",
  "Printer Repair",
  "Mobile Repair",
  "Tablet Repair",
  "Internet Setup",
  "WiFi Installation",
  "Network Repair",
  "Software Installation",
  "Door Installation",
  "Window Repair",
  "Furniture Assembly",
  "Modular Kitchen Service",
  "Tiles Installation",
  "Marble Polishing",
  "Waterproofing",
  "False Ceiling Work",
  "Interior Design",
  "Exterior Design",
  "Wallpaper Installation",
  "Curtain Installation",
  "Iron Welding",
  "Gate Repair",
  "Steel Fabrication",
  "Aluminium Work",
  "Solar Panel Installation",
  "Solar Maintenance",
  "Cement Work",
  "Brick Work",
  "Mason Service",
  "Drain Cleaning",
  "Septic Tank Cleaning",
  "Borewell Repair",
  "Motor Repair",
  "Pump Repair",
  "Gas Pipeline Repair",
  "Chimney Cleaning",
  "Chimney Repair",
  "Aquarium Cleaning",
  "Pet Grooming",
  "Dog Walking",
  "Baby Sitting",
  "Elder Care",
  "Nursing Service",
  "Physiotherapy",
  "Yoga Trainer",
  "Gym Trainer",
  "Dance Trainer",
  "Music Teacher",
  "Home Tutor",
  "Cook Service",
  "Event Decoration",
  "Photography",
  "Videography",
  "DJ Service",
  "Wedding Planning",
  "Birthday Decoration",
  "Catering Service",
  "Laundry Service",
  "Dry Cleaning"
];

const services = serviceNames.map((item, index) => ({
  name: item,

  description:
    `${item} provided by experienced professionals.`,

  image:
    `https://picsum.photos/600/400?random=${index+1}`,

  minimumPrice: 249,
}));

module.exports = services;